spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-product
    username: postgres
    password: pasha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  config:
    import: configserver:http://localhost:8888
server:
  port: 8081
management:
  tracing:
    sampling:
      probability: 0.0
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka