spring:
  application:
    name: ms-payment
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ms-product
    username: postgres
    password: pasha
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  config:
    import: configserver:http://localhost:8888
server:
  port: 8082
management:
  tracing:
    sampling:
      probability: 0.0
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
